### ISSUE TITLE
Shortcuts do not work on macOS

### ISSUE THREAD

**Issue by zikowang** [vocascan/vocascan-frontend#74]
**Describe the bug**
When you are on macOS: shortcuts to copy, cut, paste, mark, etc. text in input fields do not work.

**To Reproduce**
1. Go to login screen
2. Try to paste, copy, cut, mark, etc. text to / from any field

**Expected behavior**
Past, copy, cut, mark shortcuts should work properly.

**Screenshots**

**Please complete the following information:**

```
Version: 1.0.0
Commit: 50912ab669d7e1e6056ecdb7233d03d42ebfa591
Date: 2021-06-12T16:06:48.000Z (0 days ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

**Additional context**

**Comment by luwol03** [comment]
I have no mac, but this looks promising. https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by noctera** [comment]
We tried to fix it in this [commit](https://github.com/vocascan/vocascan-desktop/pull/76/commits/7fb2edfbe2370e92dd884b357ed48f8804b8ed4b). @zikowang, could you test if it works now, please?

**Comment by zikowang** [comment]
I've tested it. Looks good!

**Comment by luwol03** [comment]
This is now fixed in the latest version whit this commit: 7fb2edfbe2370e92dd884b357ed48f8804b8ed4b
